### ISSUE TITLE
Need your help: not fully understanding what an "activity thread" should look like

### ISSUE THREAD

**Issue by vineetparikh** [willprice/epic-kitchens-activity-stories#4]
I was introspecting the activity thread annotations using a local copy of the EPIC-Kitchens 100 extension, and the thread annotations don't seem to fit the definition of "moving between different activities/contexts". 

For context, based on the README given in this repository, I've divided the frame annotations by 30FPS to get a rough timestamp before qualitatively observing videos in EK100 at this timestamp (to verify frame alignment) along with multiplying by 50FPS (to get original frame IDs) and quantitatively clustering frames and observing mis-clustered frames in EK100, and I'm finding that there are many situations where clips are annotated in different threads even though they intuitively should be part of the same thread.

For instance, story 1445 (washing rice, emptying the water in the sink, then filling and washing the rice again) feels like it should be part of 1 thread with 3 actions (washing rice) as opposed to being split into three separate threads. Story 1 (putting oats in a pan) seems to be split into two threads despite the two threads having the same effective content (the first thread is the first scoop of oats into a pan, the second thread is the second scoop: I understand that these are both actions, but does a thread consist of multiple actions or is the possibility that multithreading/unweaving refers to returning to actions currently in progress, so each thread is effectively one action or less?)

Is there anything I'm misunderstanding about either how I'm interpreting the annotations or the definition of a thread?

**Comment by dimadamen** [comment]
There's no link between the action start/end times and the threads. The same action could be in various threads - take for example the action of putting something away, it typically includes changing the focus from cooking to storage, and thus could have been separated into two threads. 
As shown in our supplementary, each 10 clips were given to a human annotator and asked to be split based on the annotators' belief that the camera wearer has changed their goal. They were not given any actions or asked to use the action labels at all. 
I am unable to confirm the exact examples you have given at the moment. It is unlikely that washing the rice was separated into various threads, because this should be within the same thread. I am unable to verify whether that's a mistake in mapping the frames or an error in the annotations. Unfortunately the first author is no longer available to answer these detailed questions so I am unable to assist with exactly verifying your code. 

To re-iterate, action clips can occur in various threads, however the same goal should exist within one thread. There's no link between the clip (which is 1 second) and the action. The same clip can be across actions and it was treated as a unit in annotating the threads.
